fixed some small typo and added some extra detail to comp409
AllanWang/McGill-Public pull request #7
Opened 2021-02-26 02:29 UTC by shubymao

Hi, thank you for sharing your note with the student. I really appreciated it and have found your note extremely helpful. While I was going through your note for COMP409. I notice some missing information and wanted to add it so others can get a more complete code template. Most notably the CSH lock implementation. Let me know if these changes are alright.

2021-03-03 17:02 UTC, shubymao commented
@AllanWang ?

2021-03-05 23:04 UTC, AllanWang requested changes

2021-03-05 23:04 UTC, AllanWang commented on Comp-409/notes.md
> +        while me.next == null   // someone have just set the tail
someone `has`.

2021-03-05 23:04 UTC, AllanWang commented on Comp-409/notes.md
> +    myPred = TS(tail,me)    // set the tail to my node
Space before `me` in code; thanks for adding this line

2021-03-05 23:04 UTC, AllanWang commented on Comp-409/notes.md
> +* Only require test and set (TS)
require`s`; I would also write `Only requires TS` to stay consistent, and because people can look back at the glossary.

2021-03-05 23:04 UTC, AllanWang commented on Comp-409/notes.md
> +* Notice that nodes get moved around
Notice`s` (error in existing doc)

2021-03-05 23:04 UTC, AllanWang commented on Comp-409/notes.md
> +        //spin until you see the new node.
Space before `spin`

2021-03-05 23:20 UTC, shubymao commented
Alright, I fixed it up.

2021-03-06 01:54 UTC, merged

2021-03-06 01:54 UTC, AllanWang commented
Thanks!